# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_production',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=1000),
        ),
    ]
