# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0005_auto_20170401_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
