# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0006_userprofile_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default='test', upload_to=''),
            preserve_default=False,
        ),
    ]
