# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0007_movie_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(upload_to='review_movie/upload_img/poster/'),
        ),
    ]
