# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0008_auto_20170406_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.CharField(default=1.1, max_length=1000),
            preserve_default=False,
        ),
    ]
