# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0009_auto_20170406_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(upload_to=''),
        ),
    ]
