# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0010_auto_20170407_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
