# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0011_movie_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
