# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0013_auto_20170418_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='topic',
            field=models.CharField(default='Topic', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
