# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0015_auto_20170419_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='default/defult_profile.png', upload_to=''),
        ),
    ]
