# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0017_auto_20170419_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='score',
            new_name='rating',
        ),
    ]
