# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0018_auto_20170419_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
