# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0019_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=8000),
        ),
    ]
