# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('review_movie', '0020_auto_20170422_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerRequest',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('topic', models.CharField(max_length=50)),
                ('request', models.TextField(max_length=5000)),
                ('request_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
