# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0021_reviewerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerrequest',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
