# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0023_auto_20170423_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerrequest',
            name='confirm',
            field=models.BooleanField(choices=[('TRUE', True), ('FALSE', False), ('NONE', None)]),
        ),
    ]
