# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0024_auto_20170424_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerrequest',
            name='confirm',
            field=models.BooleanField(choices=[(True, True), (False, False), (None, None)]),
        ),
    ]
