# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0025_auto_20170424_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerrequest',
            name='confirm',
            field=models.NullBooleanField(choices=[(True, 'Confirm'), (False, 'Not Confirm')]),
        ),
    ]
