# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 10:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0027_auto_20170424_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(max_length=8000),
        ),
    ]
