# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 03:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0030_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
