# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_movie', '0031_auto_20170425_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
